config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "queries#index"

  resources :queries, only: [:index, :new, :create, :destroy]
  resources :credits, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :queries, only: [:index, :create, :destroy]
      resources :credits, only: [:index, :create, :destroy]
    end
  end
end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :user

  validate :start_date_is_date?
  validate :end_date_is_date?

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :kwh_rate, presence: true, numericality: true
  validates :kwh_credit, presence: true, numericality: true
  validates :sent_to_grid, presence: true, numericality: true
  validates :distribution_charge, presence: true, numericality: true

  before_save :get_data, :calculate

  def get_data
    @key = ENV["API_KEY"]
    @uri = URI("https://monitoringapi.solaredge.com/site/#{self.user.site_id}/energy?timeUnit=DAY&endDate=#{self.end_date}&startDate=#{self.start_date}&api_key=#{@key}")
    @response = Net::HTTP.get_response(@uri)
    @info = JSON.parse(@response.body)
    energy_dates = @info["energy"]["values"]
    @solar_total = energy_dates.map { |date| date["value"] || 0 }.reduce(:+)
  end


  def calculate
    if self.kwh_generated.nil?
      self.kwh_generated = @solar_total / 1000
    end
    self.consumed = self.kwh_generated - self.sent_to_grid
    self.savings_consumed = self.consumed * self.kwh_rate
    self.credit_grid = self.sent_to_grid * self.kwh_credit
    self.savings_before_distribution = self.savings_consumed + self.credit_grid
    self.total_savings = self.savings_before_distribution - self.distribution_charge
  end

  def self.process_totals(queries)
    totals = {
      kwh_generated: 0,
      kwh_consumed: 0,
      savings_consumed: 0,
      sent_to_grid: 0,
      credit_grid: 0,
      savings_before_distribution: 0,
      distribution_charge: 0,
      total_savings: 0
    }
    queries.each do |query|
      totals[:kwh_generated] += query.kwh_generated.to_f.round(2)
      totals[:kwh_consumed] += query.consumed.to_f.round(2)
      totals[:savings_consumed] += query.savings_consumed.to_f.round(2)
      totals[:sent_to_grid] += query.sent_to_grid.to_f.round(2)
      totals[:credit_grid] += query.credit_grid.to_f.round(2)
      totals[:savings_before_distribution] += query.savings_before_distribution.to_f.round(2)
      totals[:distribution_charge] += query.distribution_charge.to_f.round(2)
      totals[:total_savings] += query.total_savings.to_f.round(2)
    end
    return totals
  end

  def self.round_queries(queries)
    query_attributes = []
    queries.each do |q|
      cleansed_attributes = {}
      q.attributes.each do |atr, val|
        (val && val.class == BigDecimal) ? cleansed_attributes[atr] = val.to_f.round(2) : cleansed_attributes[atr] = val
      end
      query_attributes << cleansed_attributes
    end
    return query_attributes
  end

  private

  def start_date_is_date?
    unless start_date.is_a?(Date)
      errors.add(:start_date, 'must be a valid start date')
    end
  end

  def end_date_is_date?
    unless end_date.is_a?(Date)
      errors.add(:end_date, 'must be a valid end date')
    end
  end
end

app/models/query/total_calculator.rb
class TotalCalculator
  def self.calculate(queries, credits, current_user)
    @queries = queries
    @credits = credits
    if Total.any?
      Total.destroy_all
    end
    @total = Total.new
    @total.user = current_user
    @credits.each do |credit|
      if credit.user == current_user
        @total.total_savings += credit.srec_credit + credit.tax_credit
      end
    end
    @queries.each do |query|
      if query.user == current_user
        @total.kwh_generated += query.kwh_generated
        @total.kwh_consumed += query.consumed
        @total.savings_consumed += query.savings_consumed
        @total.sent_to_grid += query.sent_to_grid
        @total.credit_grid += query.credit_grid
        @total.savings_before_distribution += query.savings_before_distribution
        @total.distribution_charge += query.distribution_charge
        @total.total_savings += query.total_savings
      end
    end
    @total.save
  end
end

app/controllers/api/v1/queries_controller.rb
class Api::V1::QueriesController < ActionController::Base
  before_action :authenticate_user!

  def index
    @queries = Query.where('user_id = ?', current_user.id)
    render json: {
      queries: Query.round_queries(@queries.order(start_date: :desc)),
      user: current_user,
      totals: Query.process_totals(@queries)
    }
  end

  def create
    @query = Query.new(query_params)
    @query.user = current_user
    if @query.save
      render json: @query
    else
      render json: :nothing, status: :not_found
    end
  end

  def destroy
    @query = Query.find(params[:id])
    if @query.destroy
      render json: :success
    else
      render json: :nothing, status: :not_found
    end
  end

  private

  def query_params
    params.require(:query).permit(
      :start_date,
      :end_date,
      :kwh_rate,
      :kwh_credit,
      :sent_to_grid,
      :distribution_charge,
      :user_id
    )
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @totals = Total.all
    @credits = Credit.all
    @credit = Credit.new
    @queries = Query.all
    @query = Query.new
  end

  def create
    @queries = Query.all
    @credits = Credit.all
    @query = Query.new(query_params)
    @query.user = current_user
    if @query.save
      redirect_to root_path
    else
      flash[:notice] = "Please enter valid information."
      render :index
    end
  end

  def destroy
    @queries = Query.all
    @credits = Credit.all
    @query = Query.find(params[:id])
    @query.user = current_user
    @query.destroy
    TotalCalculator.calculate(@queries, @credits, current_user)
    redirect_to root_path
  end

  private

  def query_params
    params.require(:query).permit(
    :start_date,
    :end_date,
    :kwh_rate,
    :kwh_credit,
    :sent_to_grid,
    :distribution_charge,
    :user_id
    )
  end
end

app/views/queries/index.html.erb
<div id="queryList"></div>
<%= javascript_include_tag "appBundle" %>

app/views/queries/old.html.erb
<% if user_signed_in? %>
  <h1>Solaredge Calculator</h1>

  <p>Please enter information below:</p>

  <%= form_for(@credit) do |f| %>

    <div class="field">
      <%= f.label :tax_credit, "Tax Credit" %>
      <%= f.text_field :tax_credit %>
    </div>

    <div class="field">
      <%= f.label :srec_credit, "SREC Credit" %>
      <%= f.text_field :srec_credit %>
    </div>

    <div class="actions">
      <%= f.submit "Submit" %>
    </div>

  <% end %>


  <%= form_for(@query) do |f| %>

    <div class="field">
      <%= f.label :start_date, "Start Date" %>
      <%= f.text_field :start_date %>
    </div>

    <div class="field">
      <%= f.label :end_date, "End Date" %>
      <%= f.text_field :end_date %>
    </div>

    <div class="field">
      <%= f.label :kWh_rate, "kWh Rate" %>
      <%= f.text_field :kwh_rate %>
    </div>

    <div class="field">
      <%= f.label :kWh_credit, "kWh Credit" %>
      <%= f.text_field :kwh_credit %>
    </div>

    <div class="field">
      <%= f.label :sent_to_grid, "Sent To Grid" %>
      <%= f.text_field :sent_to_grid %>
    </div>

    <div class="field">
      <%= f.label :distribution_charge, "Distribution Charge" %>
      <%= f.text_field :distribution_charge %>
    </div>

    <div class="actions">
      <%= f.submit "Submit" %>
    </div>

  <% end %>

    <table>
      <thead>
        <tr>
          <th>Start Date</th>
          <th>End Date</th>
          <th>kWh Generated</th>
          <th>kWh Consumed</th>
          <th>Savings Consumed</th>
          <th>Sent to Grid</th>
          <th>Credit Grid</th>
          <th>Savings Before Distribution</th>
          <th>Distribution Charge</th>
          <th>Total Savings</th>
        </tr>
      </thead>
      <tbody>
        <% @queries.each do |query| %>
          <tr>
            <% if query.user == current_user %>
              <td><%= query.start_date %></td>
              <td><%= query.end_date %></td>
              <td><%= query.kwh_generated %></td>
              <td><%= query.consumed %></td>
              <td><%= query.savings_consumed %></td>
              <td><%= query.sent_to_grid %></td>
              <td><%= query.credit_grid %></td>
              <td><%= query.savings_before_distribution %></td>
              <td><%= query.distribution_charge %></td>
              <td><%= query.total_savings %></td>
              <td><%= link_to "Delete", query_path(query), method: :delete %><td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h2>Credits:</h2>
    <table>
      <thead>
        <tr>
          <th>Tax Credits</th>
          <th>SREC Credits</th>
        </tr>
      </thead>
      <tbody>
        <% @credits.each do |credit| %>
          <% if credit.user == current_user %>
            <tr>
              <td><%= credit.tax_credit %></td>
              <td><%= credit.srec_credit %></td>
              <td><%= link_to "Delete", credit_path(credit), method: :delete %><td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <h2>Totals:</h2>
    <table>
      <thead>
        <tr>
          <th>kWh Generated</th>
          <th>kWh Consumed</th>
          <th>Savings Consumed</th>
          <th>Sent to Grid</th>
          <th>Credit Grid</th>
          <th>Savings Before Distribution</th>
          <th>Distribution Charge</th>
          <th>Grand Total Savings</th>
        </tr>
      </thead>
      <tbody>
        <% @totals.each do |total| %>
          <% if total.user == current_user %>
            <tr>
              <td><%= total.kwh_generated %></td>
              <td><%= total.kwh_consumed %></td>
              <td><%= total.savings_consumed %></td>
              <td><%= total.sent_to_grid %></td>
              <td><%= total.credit_grid %></td>
              <td><%= total.savings_before_distribution %></td>
              <td><%= total.distribution_charge %></td>
              <td><%= total.total_savings %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <h2>Return On Investment:</h2>
    <table>
      <thead>
        <tr>
          <th>Initial Investment</th>
          <th>Return on Investment</th>
        </tr>
      </thead>
      <tbody>
        <% @totals.each do |total| %>
          <% if total.user == current_user %>
            <tr>
              <td><%= current_user.initial_investment %></td>
              <td><%= current_user.return_on_investment = current_user.initial_investment - total.total_savings %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>


<% end %>